# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-20 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='blog标题')),
                ('content', models.TextField(default='', verbose_name='博客正文')),
            ],
        ),
    ]
